# Generated by Django 3.2.3 on 2021-06-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
